Repository GazzolaLab/MiV-OS, pull requests merged in 2022-04, with the labels that each got.

#1 Cookiecutter: Initial Repository Setup
  .flake8
  .gitignore
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
  README.md
  RELEASE.md
  docs/Makefile
  docs/README.md
  docs/conf.py
  docs/guide/tutorials.rst
  docs/index.rst
  docs/make.bat
  docs/requirements.txt
  examples/main.py
  main.py
  miv/spike_analysis.py
  miv/version.py
  requirements.txt
  setup.py
Labels: documentation, enhancement

#3 Update: Initialize documentation webpage
  README.md
Labels: documentation

#5 Add GitHub actions
  .github/workflows/main.yml
Labels: enhancement

#12 fix:main yml codecoverage
  .github/workflows/main.yml
Labels: bug

#14 Filter module implementation, unittest, and documentation
  .github/workflows/main.yml
  .pre-commit-config.yaml
  Makefile
  docs/README.md
  docs/api/_toctree/FilterAPI/miv.signal.filter.ButterBandpass.rst
  docs/api/_toctree/FilterAPI/miv.signal.filter.FilterCollection.rst
  docs/api/_toctree/FilterAPI/miv.signal.filter.FilterProtocol.rst
  docs/api/signal.rst
  docs/conf.py
  docs/examples/spike_detection.rst
  docs/guide/signal_processing.ipynb
  docs/guide/spike_processing.rst
  docs/index.rst
  docs/requirements.txt
  miv/io/__init__.py
  miv/io/binary.py
  miv/signal/filter/__init__.py
  miv/signal/filter/butter_bandpass_filter.py
  miv/signal/filter/continuous_signal_filter.py
  miv/signal/filter/filter_collection.py
  miv/signal/filter/protocol.py
  miv/signal/spike/detection.py
  miv/typing.py
  requirements.txt
  setup.py
  tests/filter/mock_filter.py
  tests/filter/test_butterworth.py
  tests/filter/test_filter_collection.py
  tests/filter/test_filter_protocol.py
  tests/requirements.txt
  tests/test_modules.py
Labels: enhancement, prio:high

#18 Add spike detection module
  docs/api/_toctree/DetectionAPI/miv.signal.spike.SpikeDetectionProtocol.rst
  docs/api/_toctree/DetectionAPI/miv.signal.spike.ThresholdCutoff.rst
  docs/api/_toctree/FilterAPI/miv.signal.filter.FilterCollection.rst
  docs/api/signal.rst
  docs/conf.py
  docs/guide/signal_processing.ipynb
  miv/signal/spike/__init__.py
  miv/signal/spike/detection.py
  miv/signal/spike/protocol.py
  miv/typing.py
  tests/spike/mock_spike_detection.py
  tests/spike/test_spike_detection_protocol.py
Labels: documentation, enhancement

#19 Basic statistics doc page and summarizing modules
  docs/api/_toctree/StatisticsAPI/miv.statistics.summarizer.StatisticsSummary.rst
  docs/api/statistics.rst
  miv/statistics/__init__.py
  miv/statistics/spike_analysis.py
  miv/statistics/summarizer.py
Labels: documentation, enhancement

#17 Data set interface
  miv/io/data.py
Labels: enhancement, prio:high

#20 Update 0.0.2
  .github/workflows/main.yml
  .pre-commit-config.yaml
  .readthedocs.yaml
  Makefile
  README.md
  docs/README.md
  docs/api/_toctree/DetectionAPI/miv.signal.spike.SpikeDetectionProtocol.rst
  docs/api/_toctree/DetectionAPI/miv.signal.spike.ThresholdCutoff.rst
  docs/api/_toctree/FilterAPI/miv.signal.filter.ButterBandpass.rst
  docs/api/_toctree/FilterAPI/miv.signal.filter.FilterCollection.rst
  docs/api/_toctree/FilterAPI/miv.signal.filter.FilterProtocol.rst
  docs/api/_toctree/StatisticsAPI/miv.statistics.summarizer.StatisticsSummary.rst
  docs/api/signal.rst
  docs/api/statistics.rst
  docs/conf.py
  docs/examples/spike_detection.rst
  docs/guide/signal_processing.ipynb
  docs/guide/spike_processing.rst
  docs/index.rst
  docs/requirements.txt
  miv/io/__init__.py
  miv/io/binary.py
  miv/io/data.py
  miv/signal/filter/__init__.py
  miv/signal/filter/butter_bandpass_filter.py
  miv/signal/filter/continuous_signal_filter.py
  miv/signal/filter/filter_collection.py
  miv/signal/filter/protocol.py
  miv/signal/spike/__init__.py
  miv/signal/spike/detection.py
  miv/signal/spike/protocol.py
  miv/statistics/__init__.py
  miv/statistics/spike_analysis.py
  miv/statistics/summarizer.py
  miv/typing.py
  miv/version.py
  requirements.txt
  setup.py
  tests/filter/mock_filter.py
  tests/filter/test_butterworth.py
  tests/filter/test_filter_collection.py
  tests/filter/test_filter_protocol.py
  tests/requirements.txt
  tests/spike/mock_spike_detection.py
  tests/spike/test_spike_detection_protocol.py
  tests/test_modules.py
Labels: enhancement, prio:high

#22 data load documentation added
  docs/guide/signal_processing.ipynb
  miv/io/data.py
Labels: documentation

#21 Patch: visualization module, unittests, docs
  docs/api/_toctree/StatisticsAPI/miv.statistics.summarizer.StatisticsSummary.rst
  docs/api/_toctree/StatisticsAPI/miv.statistics.summarizer.spikestamps_statistics.rst
  docs/api/_toctree/VisualizationAPI/miv.visualization.fft_domain.plot_frequency_domain.rst
  docs/api/_toctree/VisualizationAPI/miv.visualization.waveform.extract_waveforms.rst
  docs/api/_toctree/VisualizationAPI/miv.visualization.waveform.plot_waveforms.rst
  docs/api/statistics.rst
  docs/api/visualization.rst
  docs/guide/spike_cutout.ipynb
  docs/index.rst
  miv/signal/filter/filter_collection.py
  miv/signal/spike/detection.py
  miv/statistics/summarizer.py
  miv/typing.py
  miv/visualization/__init__.py
  miv/visualization/fft_domain.py
  miv/visualization/waveform.py
  tests/filter/__init__.py
  tests/filter/test_butterworth.py
  tests/filter/test_filter_collection.py
  tests/statistics/__init__.py
  tests/statistics/test_spikestamps_statistics.py
Labels: documentation, enhancement
