Repository GazzolaLab/MiV-OS, pull requests merged in 2022-06, with the labels that each got.

#39 Update: Sample dataset and utilities to install
  docs/examples/sample_datasets.rst
  docs/index.rst
  miv/datasets/__init__.py
  miv/datasets/criticality.py
  miv/datasets/optogenetic.py
  miv/datasets/protocol.py
  miv/datasets/utils.py
Labels: documentation, enhancement, prio:mid

#44 Statistics: Inter-spike interval histogram
  docs/api/_toctree/StatisticsAPI/miv.statistics.coefficient_variation.rst
  docs/api/_toctree/StatisticsAPI/miv.statistics.firing_rates.rst
  docs/api/_toctree/StatisticsAPI/miv.statistics.interspike_intervals.rst
  docs/api/_toctree/StatisticsAPI/miv.statistics.signal_to_noise.rst
  docs/api/_toctree/StatisticsAPI/miv.statistics.spikestamps_statistics.rst
  docs/api/statistics.rst
  miv/io/binary.py
  miv/statistics/__init__.py
  miv/statistics/signal_statistics.py
  miv/statistics/spiketrain_statistics.py
  miv/statistics/summarizer.py
  tests/statistics/test_spikestamps_statistics.py
Labels: enhancement

#42 [WIP] Connectivity - cross correlation and pattern detection using cell assembly
  docs/.gitignore
  docs/guide/channel_correlation.md
  docs/index.rst
  miv/signal/filter/filter_collection.py
Labels: documentation

#48 Update v0.1.0
  README.md
  docs/.gitignore
  docs/api/_toctree/StatisticsAPI/miv.statistics.coefficient_variation.rst
  docs/api/_toctree/StatisticsAPI/miv.statistics.firing_rates.rst
  docs/api/_toctree/StatisticsAPI/miv.statistics.interspike_intervals.rst
  docs/api/_toctree/StatisticsAPI/miv.statistics.signal_to_noise.rst
  docs/api/_toctree/StatisticsAPI/miv.statistics.spikestamps_statistics.rst
  docs/api/statistics.rst
  docs/examples/sample_datasets.rst
  docs/guide/channel_correlation.md
  docs/guide/data_management.md
  docs/index.rst
  docs/overview/about.md
  docs/overview/about.rst
  docs/overview/references.rst
  miv/datasets/__init__.py
  miv/datasets/criticality.py
  miv/datasets/optogenetic.py
  miv/datasets/protocol.py
  miv/datasets/utils.py
  miv/io/binary.py
  miv/signal/filter/filter_collection.py
  miv/statistics/__init__.py
  miv/statistics/signal_statistics.py
  miv/statistics/spiketrain_statistics.py
  miv/statistics/summarizer.py
  pyproject.toml
  tests/statistics/test_spikestamps_statistics.py
Labels: documentation, enhancement, prio:high

#55 Patch CONTRIBUTING.md guideline
  CONTRIBUTING.md
  docs/README.md
Labels: logistics

#57 Statistics: PSTH implementation
  miv/statistics/spiketrain_statistics.py
  tests/statistics/test_spikestamps_statistics.py
Labels: enhancement

#53 Connectivity guide update
  docs/api/_toctree/VisualizationAPI/miv.visualization.causality.pairwise_causality_plot.rst
  docs/api/_toctree/VisualizationAPI/miv.visualization.fft_domain.plot_spectral.rst
  docs/api/causality.rst
  docs/api/visualization.rst
  docs/guide/granger_causality_psd_cpsd_coherence.md
  docs/index.rst
  miv/statistics/__init__.py
  miv/statistics/pairwise_causality.py
  miv/visualization/__init__.py
  miv/visualization/causality.py
  miv/visualization/fft_domain.py
Labels: documentation

#60 Burst analysis for a single channel and plotting across channels
  docs/api/_toctree/StatisticsAPI/miv.statistics.burst.rst
  docs/api/_toctree/VisualizationAPI/miv.visualization.event.plot_burst.rst
  docs/api/statistics.rst
  docs/api/visualization.rst
  docs/guide/burst_analysis.md
  docs/index.rst
  miv/statistics/__init__.py
  miv/statistics/burst.py
  miv/visualization/__init__.py
  miv/visualization/event.py
  tests/statistics/test_burst.py
  tests/test_burst.py
Labels: documentation, enhancement

#63 Information Theory Module
  docs/api/_toctree/StatisticsAPI/miv.statistics.active_information.rst
  docs/api/_toctree/StatisticsAPI/miv.statistics.binned_spiketrain.rst
  docs/api/_toctree/StatisticsAPI/miv.statistics.block_entropy.rst
  docs/api/_toctree/StatisticsAPI/miv.statistics.conditional_entropy.rst
  docs/api/_toctree/StatisticsAPI/miv.statistics.entropy_rate.rst
  docs/api/_toctree/StatisticsAPI/miv.statistics.mutual_information.rst
  docs/api/_toctree/StatisticsAPI/miv.statistics.relative_entropy.rst
  docs/api/_toctree/StatisticsAPI/miv.statistics.shannon_entropy.rst
  docs/api/_toctree/StatisticsAPI/miv.statistics.transfer_entropy.rst
  docs/api/statistics.rst
  docs/guide/info_theory.md
  docs/index.rst
  miv/statistics/__init__.py
  miv/statistics/burst.py
  miv/statistics/info_theory.py
  miv/statistics/spiketrain_statistics.py
Labels: enhancement

#67 Fano factor
  Makefile
  docs/api/_toctree/StatisticsAPI/miv.statistics.fano_factor.rst
  docs/api/statistics.rst
  miv/statistics/spiketrain_statistics.py
  tests/statistics/test_fano_factor.py
Labels: enhancement
