Repository GazzolaLab/MiV-OS, pull requests merged in 2022-08, with the labels that each got.

#86 (#85) remove fft viz code duplication + add test for rest of the function
  Makefile
  miv/visualization/fft_domain.py
  tests/visualization/test_fft.py
Labels: enhancement, prio:high

#88 Update Tests
  .coveragerc
  miv/io/binary.py
  miv/io/data.py
  miv/signal/spike/sorting.py
  miv/statistics/burst.py
  miv/visualization/connectivity.py
  miv/visualization/waveform.py
  tests/io/mock_data.py
  tests/io/test_binary_io.py
  tests/io/test_data_manager_module.py
  tests/io/test_data_single_module.py
  tests/signal/test_sorting.py
  tests/statistics/test_burst.py
  tests/statistics/test_signal.py
  tests/test_burst.py
  tests/visualization/test_plot_connectivity.py
  tests/visualization/test_waveform.py
Labels: enhancement

#91 Audio encoding (Lyon's Ear Model + BSA)
  .github/workflows/ci-sphinx.yml
  .gitignore
  docs/api/coding.rst
  docs/guide/lyon_ear_model.md
  docs/index.rst
  miv/coding/__init__.py
  miv/coding/spatial/__init__.py
  miv/coding/temporal/__init__.py
  miv/coding/temporal/lyon.py
  miv/coding/temporal/protocol.py
  miv/coding/temporal/spiker.py
  miv/typing.py
  poetry.lock
  pyproject.toml
  tests/coding/test_ear_model.py
Labels: enhancement

#89 Update 0.2.0
  .coveragerc
  .github/workflows/ci-sphinx.yml
  .gitignore
  Makefile
  docs/api/_toctree/VisualizationAPI/miv.visualization.connectivity.plot_connectivity.rst
  docs/api/_toctree/VisualizationAPI/miv.visualization.connectivity.plot_connectivity_interactive.rst
  docs/api/coding.rst
  docs/api/visualization.rst
  docs/guide/connectivity_network.md
  docs/guide/lyon_ear_model.md
  docs/index.rst
  miv/coding/__init__.py
  miv/coding/spatial/__init__.py
  miv/coding/temporal/__init__.py
  miv/coding/temporal/lyon.py
  miv/coding/temporal/protocol.py
  miv/coding/temporal/spiker.py
  miv/io/binary.py
  miv/io/data.py
  miv/signal/spike/sorting.py
  miv/statistics/burst.py
  miv/typing.py
  miv/visualization/__init__.py
  miv/visualization/connectivity.py
  miv/visualization/fft_domain.py
  miv/visualization/waveform.py
  poetry.lock
  pyproject.toml
  tests/coding/test_ear_model.py
  tests/io/mock_data.py
  tests/io/test_binary_io.py
  tests/io/test_data_manager_module.py
  tests/io/test_data_single_module.py
  tests/signal/test_sorting.py
  tests/statistics/test_burst.py
  tests/statistics/test_signal.py
  tests/statistics/test_spikestamps_statistics.py
  tests/test_burst.py
  tests/visualization/mock.py
  tests/visualization/test_causality.py
  tests/visualization/test_event.py
  tests/visualization/test_fft.py
  tests/visualization/test_plot_connectivity.py
  tests/visualization/test_raw_signal.py
  tests/visualization/test_waveform.py
Labels: logistics

#93 Test Cases + Bug fix binned_spiketrain
  docs/guide/connectivity_network.md
  miv/statistics/spiketrain_statistics.py
  miv/visualization/connectivity.py
  tests/statistics/test_fano_factor.py
  tests/statistics/test_info_theory.py
  tests/statistics/test_spikestamps_statistics.py
  tests/visualization/test_plot_connectivity.py
Labels: bug

#94 Shift documentation theme to PyData
  .coveragerc
  .github/workflows/ci-sphinx.yml
  .gitignore
  Makefile
  README.md
  RELEASE.md
  docs/_templates/miv-switcher.html
  docs/api/_toctree/VisualizationAPI/miv.visualization.connectivity.plot_connectivity.rst
  docs/api/_toctree/VisualizationAPI/miv.visualization.connectivity.plot_connectivity_interactive.rst
  docs/api/coding.rst
  docs/api/index.rst
  docs/api/visualization.rst
  docs/conf.py
  docs/discussion/index.rst
  docs/examples/spike_detection_rst.temp
  docs/guide/connectivity_network.md
  docs/guide/index.rst
  docs/guide/lyon_ear_model.md
  docs/guide/sample_datasets.rst
  docs/index.rst
  docs/overview/index.md
  miv/coding/__init__.py
  miv/coding/spatial/__init__.py
  miv/coding/temporal/__init__.py
  miv/coding/temporal/lyon.py
  miv/coding/temporal/protocol.py
  miv/coding/temporal/spiker.py
  miv/io/binary.py
  miv/io/data.py
  miv/signal/spike/sorting.py
  miv/statistics/burst.py
  miv/typing.py
  miv/visualization/__init__.py
  miv/visualization/connectivity.py
  miv/visualization/fft_domain.py
  miv/visualization/waveform.py
  poetry.lock
  pyproject.toml
  tests/coding/test_ear_model.py
  tests/io/mock_data.py
  tests/io/test_binary_io.py
  tests/io/test_data_manager_module.py
  tests/io/test_data_single_module.py
  tests/signal/test_sorting.py
  tests/statistics/test_burst.py
  tests/statistics/test_signal.py
  tests/statistics/test_spikestamps_statistics.py
  tests/test_burst.py
  tests/visualization/mock.py
  tests/visualization/test_causality.py
  tests/visualization/test_event.py
  tests/visualization/test_fft.py
  tests/visualization/test_plot_connectivity.py
  tests/visualization/test_raw_signal.py
  tests/visualization/test_waveform.py
Labels: documentation, enhancement

#90 Initial implementation of MiV HDF5-based data format
  .github/workflows/ci-sphinx.yml
  .github/workflows/main.yml
  .gitignore
  docs/api/io.rst
  docs/guide/data_structure/hdf5_based_data_format.md
  docs/guide/index.rst
  examples/README.md
  examples/post_processing/spike_detection.py
  miv/io/file/__init__.py
  miv/io/file/read.py
  miv/io/file/write.py
  poetry.lock
  pyproject.toml
  scripts/README.md
  scripts/convert_open_ephys_to_miv.py
  tests/io/test_binary_io.py
  tests/io/test_file_read.py
  tests/io/test_file_write.py
Labels: enhancement, prio:high

#99 TTL event readout from OpenEphys dataset
  docs/.gitignore
  docs/guide/index.rst
  docs/guide/read_TTL_events.md
  docs/index.rst
  miv/datasets/ttl_events.py
  miv/io/binary.py
  miv/io/data.py
  miv/visualization/waveform.py
  tests/io/mock_data.py
  tests/io/test_binary_io.py
Labels: enhancement

#102 Add core datatypes: SpikeTrain
  miv/core/__init__.py
  miv/core/spiketrain.py
  tests/core/test_spiketrain.py
Labels: enhancement

#103 Setup dependabot
  .github/dependabot.yml
  poetry.lock
  pyproject.toml
Labels: prio:mid, logistics
