Repository GazzolaLab/MiV-OS, pull requests merged in 2023-02, with the labels that each got.

#193 Doc: how to use change-point detection algorithm
  docs/guide/change_detection.md
  poetry.lock
  pyproject.toml
Labels: documentation

#192 Update contributing guideline
  CONTRIBUTING.md
Labels: logistics

#190 Make `load_fragments` to be default behavior for `load`
  Makefile
  docs/guide/index.rst
  docs/guide/read_data_fragment.md
  docs/tutorial/signal_processing.md
  miv/io/data.py
  miv/io/intan/data.py
  miv/io/protocol.py
  poetry.lock
  pyproject.toml
  tests/io/mock_data.py
  tests/io/test_auto_channel_mask.py
  tests/io/test_data_single_module.py
Labels: documentation, enhancement

#194 Extend CI target to cover update branches
  .github/workflows/main.yml
Labels: logistics

#197 Update 0.2.4
  .github/workflows/ci-sphinx.yml
  .github/workflows/main.yml
  Makefile
  RELEASE.md
  docs/api/core.rst
  docs/api/index.rst
  docs/api/sorting.rst
  docs/guide/change_detection.md
  docs/guide/index.rst
  docs/guide/read_TTL_events.md
  docs/guide/read_data_fragment.md
  docs/tutorial/signal_processing.md
  miv/cli/README.md
  miv/cli/convert_open_ephys_to_miv.py
  miv/cli/miv_extract_spiketrain.py
  miv/core/spikestamps.py
  miv/io/binary.py
  miv/io/data.py
  miv/io/intan/data.py
  miv/io/protocol.py
  miv/signal/similarity/__init__.py
  miv/signal/similarity/distance.py
  miv/signal/similarity/dtw.py
  miv/signal/similarity/protocol.py
  miv/signal/similarity/simple.py
  miv/statistics/spiketrain_statistics.py
  miv/typing.py
  miv/visualization/causality.py
  miv/visualization/waveform.py
  poetry.lock
  pyproject.toml
  tests/core/test_core_spikestamps.py
  tests/io/mock_data.py
  tests/io/test_auto_channel_mask.py
  tests/io/test_binary_io.py
  tests/io/test_data_single_module.py
  tests/spike/test_simple_similarity_matrix.py
  tests/statistics/test_spikestamps_statistics.py
Labels: documentation, enhancement

#213 [Feature 0.3.0] Caching operations
  docs/.gitignore
  docs/api/_toctree/FilterAPI/miv.signal.events.waveform.ExtractWaveforms.rst
  docs/tutorial/signal_processing.md
  docs/tutorial/spike_cutout.md
  miv/core/datatype/signal.py
  miv/core/operator/cachable.py
  miv/core/operator/operator.py
  miv/core/pipeline.py
  miv/core/wrapper.py
  miv/signal/events/waveform.py
  miv/signal/filter/butter_bandpass_filter.py
  miv/signal/filter/median_filter.py
  miv/signal/spike/detection.py
Labels: enhancement
